### PR TITLE
Animal Quiz.py

### PR DESCRIPTION
**Pull request by PranjalSahu295**
Created with Python

### CODE REVIEW

**Comment by Dev-Mehta** [comment]
How is this related to this project?

**Comment by PranjalSahu295** [comment]
It`s made with Python

**Comment by Dev-Mehta** [comment]
> It`s made with Python

@PranjalSahu295 it doesn't mean it adds anything to the project. 😃

**Comment by PranjalSahu295** [comment]
Yes

**Review by ShahStavan — COMMENTED** [review]
Just because it's made in python it doesn't mean it's related to the project :)
Why don't you send a merge pull request to OpenCV and the official PYTHON repo, it will definitely add some value to their project.

**Comment by PranjalSahu295** [comment]
Thank you!

**Pull request closed without merging**
